### ISSUE TITLE
Bug found in javascript

### ISSUE THREAD

**Issue by ShadyShawkat** [topeogunleye/Portfolio#33]
In JavaScript, it's better to use the `DOMContentLoaded` event and put your code inside of it. Especially when you need to query select elements or append elements to other elements. The `DOMContentLoaded` event makes sure that all the DOM is loaded and ready to go for querying.

**Comment by topeogunleye** [comment]
Hey @ShadyShawkat, thank you for taking the time to check out my project. 🙏🏻
I'll definitely consider your feedback.
