### ISSUE TITLE
Peer to Peer Code Review - Week 9 - Day 2

### ISSUE THREAD

**Issue by benjp009** [topeogunleye/Portfolio#38]
# 👋  @topeogunleye 

### Great work on your portfolio,

It would be good to improve the CSS of your page to center pictures and popup windows to look better for the viewers. 
Increase width size of the image for the popup

**Comment by topeogunleye** [comment]
Hey @benjp009, thank you for taking the time to check out my project. 🙏🏻
I'll definitely consider your feedback.
